[package]
name = "cryptopals"
version = "0.1.0"
authors = ["David McDonald <davidmcdonald@Davids-MacBook-Pro.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
itertools = "0.10.5"
